[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
identifier = "Nef9el56x3"
weight = 9_999


[[main]]
name = "Posts"
pageRef = "posts"
identifier = "Aswf9el56x3"
weight = 9_990


[[footer]]
none = "none"
